### ISSUE TITLE
Duplicate container names and indeterminate behavior

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#726] opened 2020-04-10 07:44 UTC
## 🐛 Bug Report

Given this simple opspec

```yml
name: foo
run:
    parallel:
        - container:
            name: bar
            image: {ref: alpine}
            cmd: [sleep, 100000]
        - container:
            name: bar
            image: {ref: alpine}
            cmd: [sleep, 100000]
```

What will happen if another op calls `http://bar`?

More seriously, if I reference an external op with a named container, how do I know if a container name I use conflicts with a container name it uses?

**Comment by chrisdostert** [comment] 2020-04-10 16:23
@apexskier  thanks for filing. 

This is currently by design.
Documented behavior is [if multiple containers are given the same name, network requests will be distributed (load balanced) across them.](https://opctl.io/docs/opspec/reference/structure/op-directory/op/call/container/index#name)


What's your reason for filing? Designs can be revisited.

**Comment by chrisdostert** [comment] 2020-04-18 20:01
@apexskier 👆did you have a specific use case you needed this behavior to change? Probably going to close this if not.

**Comment by chrisdostert** [comment] 2020-11-03 16:34
Because it's documented behavior i'm going to close this in order to keep issues tidy. I'm sure over time use cases and implementations will evolve but at present this is working as expected.

**Closed by chrisdostert** 2020-11-03 16:34 UTC
