### ISSUE TITLE
"too many open files" error encountered when run via cron

### ISSUE THREAD

**Issue by poppuyo** [opctl/opctl#289] opened 2017-08-10 05:22 UTC
Environment:
Ubuntu 17.04 
$ docker -v
Docker version 17.06.0-ce, build 02c1d87
$ opctl -v
0.1.20

Note, this is running in cron:

Command
```
/usr/bin/flock -n /tmp/email.lockfile ~/testsrc/email-handler/run-from-cron.sh >> ~/logs/email-handler.log
```

run-from-cron.sh:
```sh
#!/bin/sh
cd "${0%/*}"
/usr/local/bin/opctl --nc run init
```

init.op:
```yaml
name: init
description: inits the email-handler prereqs
# inputs:
#   srcDir:
#     dir:
#       default: .
#       description: directory containing the app
# outputs:
#   srcDir:
#     dir:
#       description: directory containing the app
run:
  container:
    cmd: [ npm, install ]
    #dirs:
    #  /src: srcDir
    image: { ref: 'node:8-alpine' }
    workDir: /src

```

Error:
```
OpErred Id='2567a7add6234c7449f61960b4bfb474' PkgRef='init' Timestamp='2017-08-08T17:28:01Z' Msg='
-
  Error(s):
    - open /home/jason/testsrc/email-handler/.opspec/init/op.yml: too many open files
-'

OpEnded Id='2567a7add6234c7449f61960b4bfb474' PkgRef='init' Outcome='FAILED' Timestamp='2017-08-08T17:28:01Z'
```

**Comment by poppuyo** [comment] 2017-08-10 05:23
`opctl node kill` brings opctl responsiveness back, so in that sense it's *recoverable*

**Comment by poppuyo** [comment] 2017-08-10 05:25
upgraded to `0.1.21-alpha.82`, i'll comment back here on whether it fails there too

**Comment by poppuyo** [comment] 2017-08-10 23:26
`0.1.21-alpha.82` still runs into the same error:

```
OpErred Id='56b5965bf23748df9d0d0c1e85cd7407' PkgRef='/home/jason/testsrc/email-handler/.opspec/init' Timestamp='2017-08-10T22:19:01Z' Msg='open /home/jason/testsrc/email-handler/.opspec/init/op.yml: too many open files'

OpEnded Id='56b5965bf23748df9d0d0c1e85cd7407' PkgRef='/home/jason/testsrc/email-handler/.opspec/init' Outcome='FAILED' Timestamp='2017-08-10T22:19:01Z'
```

**Comment by poppuyo** [comment] 2017-08-22 18:28
Looks like it still occurs (or may be hitting a different issue with the same symptoms) in 
```0.1.21-alpha.85```

```
From jason@vijaya  Tue Aug 22 03:01:31 2017
Return-Path: <jason@vijaya>
X-Original-To: jason
Delivered-To: jason@vijaya
Received: by vijaya (Postfix, from userid 1000)
	id 838B7619CD; Tue, 22 Aug 2017 03:01:31 -0700 (PDT)
From: root@vijaya (Cron Daemon)
To: jason@vijaya
Subject: Cron <jason@vijaya> /usr/bin/flock -n /tmp/email.lockfile ~/testsrc/email-handler/run-from-cron.sh >> ~/logs/email-handler.log
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/jason>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=jason>
Message-Id: <20170822100131.838B7619CD@vijaya>
Date: Tue, 22 Aug 2017 03:01:31 -0700 (PDT)

OpErred Id='3af34878f23a497dbd4647eb06f42a12' PkgRef='/home/jason/testsrc/email-handler/.opspec/run' Timestamp='2017-08-22T10:00:01Z' Msg='open /home/jason/testsrc/email-handler/.opspec/run/op.yml: too many open files'

OpEnded Id='3af34878f23a497dbd4647eb06f42a12' PkgRef='/home/jason/testsrc/email-handler/.opspec/run' Outcome='FAILED' Timestamp='2017-08-22T10:00:01Z'

^C
jason@vijaya:~/testsrc/email-handler$ opctl -v
0.1.21-alpha.85

```

**Comment by chrisdostert** [comment] 2017-10-20 15:56
Closing due to age & no luck in reproducing it : / 

We can re-open if it occurs more broadly or you get motivated to dig into it again

**Closed by chrisdostert** 2017-10-20 15:56 UTC
Labels: defect
