### ISSUE TITLE
Make opctl ls error if invalid ops are encountered

### ISSUE THREAD

**Issue by zimnyjakub** [opctl/opctl#708] opened 2020-03-13 14:17 UTC
## 🐛 Bug Report
When you put in an error inside of an op and it does not validate via `opctl run` it also does not show up in `opctl ls`

## To Reproduce

Given an example op.yml:

```
name: build
inputs:
  appDir:
    dir:
      default: .
run:
  serial:
    - container:
        dirs:
          /app: $(appDir)
        image: { ref: node:12.13-alpine }
        workDir: /app
        cmd:
          - yarn
          - install
    - container:
        dirs:
          /app: $(appDir)
        image: { ref: node:12.13-alpine }
        workDir: /app
        envVars: # <- error is here
        cmd:
          - yarn
          - install
```

when running `opctl ls`

then it shows empty list

## Expected behavior

I expect `opctl ls` to still show the op even if it contains errors. Optionally i can be warned that specification has error in yml file.

I only found out that the op has an error when tried to run it 

## Actual Behavior

`opctl ls` should show all ops, regardless if yml file has an error or not

**Comment by chrisdostert** [comment] 2020-03-13 15:27
Thanks @zimnyjakub . This is duplicate of https://github.com/opctl/opctl/issues/255 but your ticket is more complete so let's close that one and leave this one open. 

This behavior was originally by design; only syntactically valid ops are shown. When you say you'd like it to show valid and invalid both, how would you propose we indicated one was valid vs invalid in the output, or would you not?

**Comment by zimnyjakub** [comment] 2020-03-16 20:26
My use case here was:

* I create a new op
* I want to verify if I've created the catalog structure correctly
* Due to a human error I make a mistake in the yml file
* I can't see the op in `opctl ls` and therefore I think I misplaced the yml file, whereas I just made a syntax error

I don't think putting the information if its valid or not is necessary from users perspective, as the next step would be to run new op - which would reveal an error anyway. I can imagine also that making a stat on file is quicker and easier rather than loading, parsing and validating the file by `ls` - I leave it all up to you though

**Comment by chrisdostert** [comment] 2020-03-16 20:34
yeah currently we do validate each candidate when considering what to show in ls and ignore those that don't pass. `opctl op validate xxx` was meant to be used to test if ops are valid. 

Your flow has seemed to be a not uncommon path people take though and they're not aware of `opctl op validate xxx` so I do think we should change the behavior of ls.. I just then wonder if we should then at least indicate it's valid or not

**Comment by zimnyjakub** [comment] 2020-03-16 20:38
Well, from users perspective something as column "valid" with tick or X emoji would be useful, although not required. Usually I imagine users "machine gun" commands one after the other so that information will pop up in their terminal quite quickly, so that would be duplication information then

I personally "list" ops, I don't care if they are valid or not - I guess you can apply SRP here

**Comment by chrisdostert** [comment] 2020-03-16 20:42
maybe opctl ls should just blow up.. like what might happen in a compiled language

**Comment by chrisdostert** [comment] 2020-03-16 20:43
you're asking it to fullfill a request it cannot satisfy because the source you're pointing it at isn't valid

**Comment by chrisdostert** [comment] 2020-03-16 20:45
I kinda like that.. what do you think?

**Comment by zimnyjakub** [comment] 2020-03-17 07:29
That also sounds good, its totally up to you though

If I were doing this i'd be looking at linux tools, separate each operation as far from each other as possible. Then list should run on valid or invalid ops, because its only dependcy is system.stat for example

**Comment by chrisdostert** [comment] 2020-03-17 15:47
I see no value in `opctl ls` simply returning items from the local filesystem; plenty of existing tools for that ala `tree`, `ls` or whatever. 

Currently, given a reference to a directory, either remote or local, it will return operations contained therein. Invalid operations; linux `ls` would not return invalid files I don't think.

**Closed** 2020-05-03 23:06 UTC
Labels: UX
