### ISSUE TITLE
Optional directory input is required

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#752] opened 2020-04-28 11:29 UTC
## 🐛 Bug Report

When I write an op with a defaulted (optional) directory argument, opctl fails validation if it's composed into another op.

## To Reproduce

**bar/op.yml**

```yml
name: bar
inputs:
  bar:
    dir:
      default: .
run:
  container:
    image: { ref: 'alpine' }
    cmd: ["echo", "hello world"]
```

**foo/op.yml**

```yml
name: foo
run:
  op:
    ref: ../bar
```

run `opctl run foo`

## Expected behavior

Running `opctl run foo` and `opctl run bar` run the ops successfully.

## Actual Behavior

Running `opctl run foo` results in a validation error "bar: required".

<details>

```
cameronlittle@Chehalis:~/Dev/test
▻ opctl run foo
OpStarted Id='caaadc8735654f24baa6dec103ff9f07' OpRef='/Users/cameronlittle/Dev/test/foo' Timestamp='2020-04-28T11:25:04Z'

OpErred Id='caaadc8735654f24baa6dec103ff9f07' OpRef='/Users/cameronlittle/Dev/test/foo' Timestamp='2020-04-28T11:25:04Z' Msg='unable to interpret call to ../bar; error was: 
-
  validation error(s):

    - bar: required

-'

OpEnded Id='caaadc8735654f24baa6dec103ff9f07' OpRef='/Users/cameronlittle/Dev/test/foo' Outcome='FAILED' Timestamp='2020-04-28T11:25:04Z'


1 ↩
cameronlittle@Chehalis:~/Dev/test
▻ opctl run bar
OpStarted Id='5590e3ecd7964b35a6f6c12a399bd132' OpRef='/Users/cameronlittle/Dev/test/bar' Timestamp='2020-04-28T11:25:14Z'

ContainerStarted Id='fc51f3e4656e4ad69ca8df2566997e65' OpRef='/Users/cameronlittle/Dev/test/bar' Timestamp='2020-04-28T11:25:14Z'

latest: Pulling from library/alpine
Digest: sha256:9a839e63dad54c3a6d1834e29692c8492d93f90c59c978c1ed79109ea4fb9a54
Status: Image is up to date for alpine:latest
hello world
ContainerExited Id='fc51f3e4656e4ad69ca8df2566997e65' OpRef='/Users/cameronlittle/Dev/test/bar' ExitCode='0' Timestamp='2020-04-28T11:25:17Z'

OpEnded Id='5590e3ecd7964b35a6f6c12a399bd132' OpRef='/Users/cameronlittle/Dev/test/bar' Outcome='SUCCEEDED' Timestamp='2020-04-28T11:25:17Z'
```

</details>

**Comment by chrisdostert** [comment] 2020-04-28 15:39
Thanks for filing. This is actually working as intended/documented; see https://opctl.io/docs/reference/opspec/op-directory/op/parameter/dir#default and https://opctl.io/docs/reference/opspec/op-directory/op/parameter/file#default. 
specifically the "relative path defaults are ignored when an op is called from an op as there is no current working directory." bits. 

I agree it's not peoples expectation without reading the docs and it would be great to remove that, but in your example, what would you propose `default: .` resolve to?

**Comment by apexskier** [comment] 2020-04-29 08:01
Okay, I missed that.

In my case, I expected this to still apply:

> the value is interpreted from the current working directory at the time the op is called.

There's not really ambiguity to that statement, whether or not the op is called from another op. Ops can't change working directories, and it's not relative to the op directory, so it seems like it should always be true.

**Comment by chrisdostert** [comment] 2020-04-29 21:01
trouble with that is then the workdir where the root operation is called becomes a global variable accessible from any op in the graph without it being explicitly passed.

**Comment by chrisdostert** [comment] 2021-08-07 22:43
closing; it doesn't seem there's any actions outstanding.

**Closed by chrisdostert** 2021-08-07 22:43 UTC
Labels: ux
